### ISSUE TITLE
Error in VLC: "Your input can't be opened"

### ISSUE THREAD

**Issue by samjmckenzie** [blaise-io/acelink#1]
This error appears when trying to open a stream.  
[Image](https://i.imgur.com/Gqq8E1v.png) 
"VLC is unable to open the MRL 'http://127.0.0.1:6878/ace/getsream" 
Docker is installed.
Any suggestions?

**Comment by blaise-io** [comment]
@samjmckenzie  Does it work when you double click the item again inside VLC? If not, what's the value of `is_live` and `error` in`http://127.0.0.1:6878/ace/getstream?format=json&id=<ace stream hash>`? (open in your browser, replace `<hash>`)

**Comment by samjmckenzie** [comment]
I've updated to 1.0.1. The issue still exists. The JSON result was
`
{
   "response": null,
   "error": "failed to load content"
}
`
No `is_live` key for some reason. I've tested the stream on my phone, and it definitely works.

**Comment by blaise-io** [comment]
@samjmckenzie Can you privately mail me the stream hash so I can debug? blaisekal gmail.com

**Comment by samjmckenzie** [comment]
Sure. I will do that later.

**Comment by samjmckenzie** [comment]
Any progress yet?

**Comment by blaise-io** [comment]
@samjmckenzie I fixed registering media libraries in [Ace Link 1.1.1](https://github.com/blaise-io/acelink/releases/download/1.1.1/Ace.Link.1.1.1.dmg) that Ace Stream uses to re-encode streams. It could fix your issue, but I'm not sure because I don't have streams to reproduce the original issue with.

**Comment by samjmckenzie** [comment]
That seems to have fixed it. Thanks!
