### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by azoreseuropa** [blaise-io/acelink#11]
Have you improve Ace Link that doesn't require Docker as you said you would ? Love Ace Link. :)

**Comment by blaise-io** [comment]
I'm trying to get it working with Wine, so with Windows virtualization, but I'm not certain it will be an improvement in size and stability.

**Comment by joelbernstein** [comment]
I think you're much better off sticking with the Docker approach. That way you have a native Linux acestream engine. Running the windows GUI client via WINE is going to be slow (lots of cpu call translation etc, stuff that ought to be optimised in asm isn't) and give less flexible results.

**Comment by blaise-io** [comment]
@joelbernstein you're right, I came to similar conclusions.

 - First of all I couldn't get the server-only version working. Engine would start, but would return a Python missing file error
 - Full version opens ads using your default browser in the host OS
 - Ace stream in combination with wine does a bad job cleaning up after itself, it sometimes it leaves processes running
