### ISSUE TITLE
Can't get the docker image

### ISSUE THREAD

**Issue by uri200** [blaise-io/acelink#15]
Hello,

Thanks for doing this container!!!

I was able to run your docker image using the second command you have on the readme (to use other viewers different than VLC). But when I try to run the script I get an error with a missing image name. It looks like the script is not able to get the image you wanted to use. Maybe you have it in your cache and that is why it is working for you?

```
╭─ ~/Downloads/acelink-master/Ace Link                                            ✔ | at 20:01:00
╰─ ./StartDocker.sh
Docker image:
Acestream hash:
Docker is running
Pull Docker image
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry
```

Thanks!

**Comment by blaise-io** [comment]
Hello @uri200, StartDocker.sh is for internal use only. If you only want to run Ace Stream in Docker, you don't need anything from this project. [Just run `docker run -p 6878:6878 blaiseio/acestream` in a terminal as described here](https://github.com/blaise-io/acelink#ace-stream-server-only). I will  clarify that section to prevent condusion.
