### ISSUE TITLE
Only shows start of stream

### ISSUE THREAD

**Issue by alexreg** [blaise-io/acelink#19]
I was trying to use Ace Link a few days ago to view a stream and it seemed to load up the stream fine but I only got the initial frame (at the start of the very stream, not the present one in time). It remained that way indefinitely. No sound either.

**Comment by blaise-io** [comment]
Did you have this issue with one particular stream, or with multiple streams?

**Comment by alexreg** [comment]
Multiple streams, I'm afraid.

**Comment by blaise-io** [comment]
I was not able to reproduce your issue, but you could try [1.5.0](https://github.com/blaise-io/acelink/releases/tag/1.5.0) that was released today.

**Comment by alexreg** [comment]
Okay, I'll let you know how that goes next time I try a stream, thanks.

**Comment by alexreg** [comment]
Ah, is the Homebrew cask updating soon?

**Comment by blaise-io** [comment]
Yes, it’s updated

**Comment by acoks9** [comment]
I have the same issue (MacOS 10.15.3) after Docker update

**Comment by blaise-io** [comment]
When this happens next time, please email me (blaisekal@gmail.com) the ace stream id.

**Comment by alexreg** [comment]
Sure, will do. Cheers.

**Comment by blaise-io** [comment]
I'm sorry people, I cannot fix this for you. I got a couple of emails and debugged a couple of streams, but in all cases they were streams where the only peers available served the same X seconds of video, presumably because the server shut down.
