### ISSUE TITLE
IINA/mpv support

### ISSUE THREAD

**Issue by vit9696** [blaise-io/acelink#24]
Hello, could you implement IINA/mpv support instead of VLC? Thanks!

**Comment by blaise-io** [comment]
I probably won't support other players in the near future, but you could either

1. Run `docker run -p 6878:6878 blaiseio/acestream` in Terminal.app and then run `open -a IINA http://127.0.0.1:6878/ace/getstream?id=<acestream hash>` in another Terminal tab (or open IINA and open URL `http://127.0.0.1:6878/ace/getstream?id=<acestream hash>`).
2. Fork this project, change [line 66 of StartDocker.sh](https://github.com/blaise-io/acelink/blob/master/Ace%20Link/StartDocker.sh#L66), build the project using `make archive` using the Makefile in this project, or build using Xcode.

**Comment by artexhibit** [comment]
@vit9696 Thank you! Works perfect with IINA 👌🏻

**Comment by blaise-io** [comment]
@artexhibit @vit9696  You can now select IINA in version 2.0.0.
