### ISSUE TITLE
Acestream engine cache clean

### ISSUE THREAD

**Issue by evmurashov** [blaise-io/acelink#31]
Hello, 
I noticed, that acestream cache in docker container is not deleted after restart. So I suggest a script to clean it. I think it should run together with the container.

```
#!/bin/bash

echo CACHE SIZE
du -h ~/.ACEStream/.acestream_cache
echo CHECKING live.* files
LIVE=$(ls -al ~/.ACEStream/.acestream_cache | grep live.*)
if [ -z "$LIVE" ]
then echo NOTHING TO CLEAN
else rm ~/.ACEStream/.acestream_cache/live.*
     echo DONE
     echo FOLDER SIZE AFTER CLEAN
     du -h ~/.ACEStream/.acestream_cache
fi
echo CHECKING hls.* files
HLS=$(ls -al ~/.ACEStream/.acestream_cache | grep hls.*)
if [ -z "$HLS" ]
then echo NOTHING TO CLEAN
else rm ~/.ACEStream/.acestream_cache/hls.*
	echo DONE
	echo CACHE SIZE AFTER CLEAN
	du -h ~/.ACEStream/.acestream_cache
fi
```

**Comment by blaise-io** [comment]
Hey @evmurashov, do you run the Docker using the Ace Link interface? Because the data should be trashed after exiting due to the `--rm` flag: https://github.com/blaise-io/acelink/blob/master/Ace%20Link/StartDocker.sh#L37

**Comment by evmurashov** [comment]
No, I use only engine without Ace Link

**Comment by blaise-io** [comment]
I'd just run the command with --rm then as shown in the readme I just updated: https://github.com/blaise-io/acelink/commit/431c593285ae6a56f35bcf1bb52ffbe5aa2f5809

**Comment by MaikolCid** [comment]
Hello @blaise-io , could you explain what should I do to clean the cache of the AcestreamPlayer (Using Android TV) automatically when you close the link?
The problem is that when I watch a match (for example) and then I want to look a movie with Kodi, I have everytime to delete cache to be able to hear and watch it...
Thanks and Regards,
Miguel Cid.
