### ISSUE TITLE
Docker only: Way to monitor peers/bandwidth?

### ISSUE THREAD

**Issue by sotiris-bos** [blaise-io/acelink#33]
Hello, thanks for your work! I am using this on Linux to stream Acestreams through the house.

Is there any way to monitor the peers/bandwidth etc stats?

Thanks!

**Comment by blaise-io** [comment]
Ace Stream supports `--stats-report-peers` but I don't know where the report can be consumed. Might be somewhere at port 8261, but Ace Link does not map the port. 

It seems this Docker image does support reporting peers: https://github.com/magnetikonline/docker-acestream-server/blame/main/README.md#L84. 

I'm closing this issue because I won't fix it in Ace Link, but I wish you all the luck :)

**Comment by blaise-io** [comment]
While wrapping this up I encountered a way:

First visit `http://127.0.0.1:6878/ace/getstream?id=<acestream id>&format=json`

This will give you a response like 
```
{
  "response": {
    "stat_url": "http://127.0.0.1:6878/ace/stat/xxx/yyy",
    "playback_session_id": "zzz",
    "is_live": 1,
    "playback_url": "http://127.0.0.1:6878/ace/r/xxx/yyy",
    "is_encrypted": 0,
    "command_url": "http://127.0.0.1:6878/ace/cmd/xxx/yyy",
    "client_session_id": -1,
    "infohash": "xxx"
  },
  "error": null
}```

Fetch response.stat_url to get data like

```
{
  "response": {
    "status": "dl",
    "uploaded": 278528,
    "speed_down": 0,
    "speed_up": 0,
    "downloaded": 405798912,
    "playback_session_id": "yyy",
    "wan_connection_status": 0,
    "peers": 13,
    "total_progress": 0,
    "is_encrypted": 0,
    "disk_cache_stats": {
      "avail": 28991860736,
      "disk_cache_limit": 10737418240,
      "inactive_inuse": 0,
      "active_inuse": 405799116
    },
    "is_live": 1,
    "debug_level": 0,
    "client_session_id": -1,
    "infohash": "xxx",
    "selected_stream_index": 0,
    "selected_file_index": -1,
    "livepos": {
      "last": "1624103596",
      "live_first": "1624101796",
      "pos": "1624103596",
      "first_ts": "1624101796",
      "last_ts": "1624103596",
      "is_live": "1",
      "live_last": "1624103596",
      "buffer_pieces": "15"
    }
  },
  "error": null
}
```

**Comment by sotiris-bos** [comment]
Great! Thanks a lot!
