### ISSUE TITLE
macOS M1 swap memory

### ISSUE THREAD

**Issue by Patriciooo** [blaise-io/acelink#38]
Hi, I tried the two last versions of the app and it's working fine. But I have a problem with the memory swap than is in two hours like the network I/o 8gb. Its normal way ? 
Thanks. Sorry for my English.

**Comment by blaise-io** [comment]
You're likely running into an issue like https://github.com/docker/for-mac/issues/5204. If you only use Docker for Ace Link you could try to reduce the allowed resources that Docker may use in Docker's preferences. Unfortunately, I don't have access to an M1 machine.

**Comment by Patriciooo** [comment]
Thanks.

**Comment by Patriciooo** [comment]
Now is working without problem. The problem was than I have check the experimental feature : the new virtualization framework. I uncheck and now Docker is consuming a little more cpu, without ram problem, but Ace link working perfect 4k too. Thanks, I love the new historial in the app. 
( in the way looking for the problem I try adding : --memory=768m --memory-swap=768m to the run command but don't work because the container aren't the problem is the Docker Linux 64 process. as well I add to Acestream.conf : 
--live-buffer 3
--vod-buffer 3 )

Thanks.
