### ISSUE TITLE
Is there any way to work on it Raspi 4 docker?

### ISSUE THREAD

**Issue by YaPaY** [blaise-io/acelink#39]
I am getting WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

any way to do this?

**Comment by blaise-io** [comment]
Ace Link is a solution for macOS only. You could try https://github.com/sshmanko/acestream-armv7 or https://github.com/trananhtuan/acestream-armv7-docker
