### ISSUE TITLE
Acestream engine doesn't start after last update

### ISSUE THREAD

**Issue by evmurashov** [blaise-io/acelink#43]
**Describe the bug**  
Acestream engine doesn't start after last update

**Screenshots**  
![image](https://user-images.githubusercontent.com/80024729/145718505-58565787-aa9d-4c57-bbb0-83127c9926c3.png)

**Additional debug info**  
docker run --rm -p 6878:6878 blaiseio/acelink
Unable to find image 'blaiseio/acelink:latest' locally
latest: Pulling from blaiseio/acelink
58690f9b18fc: Pull complete 
b51569e7c507: Pull complete 
da8ef40b9eca: Pull complete 
fb15d46c38dc: Pull complete 
0f77662b996a: Pull complete 
282f52834eb2: Pull complete 
9d1264de63e3: Pull complete 
a4369b953fb7: Pull complete 
Digest: sha256:90ca3fb7c5d16ec023354f043649b8b9c2ea33529af45e2c092bfbbf16c77e5b
Status: Downloaded newer image for blaiseio/acelink:latest
Missing required startup options
usage: acestreamengine
                       [--client-console | --client-wx | --client-gtk | --stream-source-node | --stream-support-node | --stream-startup-node | --create-transport | --create-transport-multi | --create-hls-transport | --start-tracker | --get-infohash PATH | --get-file-info PATH | --get-file-info-with-id PATH | -v]
                       [--gui-wx | --gui-gtk] [--log-stdout | --log-stderr]
                       [--log-file PATH] [--log-max-size SIZE]
                       [--log-backup-count COUNT] [--log-file-buffer N]
                       [--log-file-encoding LOG_FILE_ENCODING]
                       [--log-syslog HOST] [--log-syslog-port PORT]
                       [--log-syslog-facility FACILITY]
                       [--log-syslog-buffer N] [--use-ffmpeg USE_FFMPEG]
                       [--download-limit DOWNLOAD_LIMIT]
                       [--upload-limit UPLOAD_LIMIT]
                       [--max-connections MAX_CONNECTIONS]
                       [--max-peers MAX_PEERS]
                       [--max-peers-limit MAX_PEERS_LIMIT]
                       [--max-timeshift-peers MAX_TIMESHIFT_PEERS]
                       [--max-upload-slots MAX_UPLOAD_SLOTS]
                       [--live-cache-type LIVE_CACHE_TYPE]
                       [--live-disk-cache-size LIVE_DISK_CACHE_SIZE]
                       [--live-mem-cache-size LIVE_MEM_CACHE_SIZE]

**Comment by blaise-io** [comment]
Thanks for reporting, please use 1.9.0 for now.

**Comment by blaise-io** [comment]
You can fix this by running `docker pull blaiseio/acelink:2.0.0`. Please confirm this fixes the issue. For a short while a bad image was live.

**Comment by evmurashov** [comment]
Same error
![image](https://user-images.githubusercontent.com/80024729/145727092-9d19868d-b520-43e1-aef2-8008577c579e.png)

**Comment by blaise-io** [comment]
Oh I'm sorry, I see now you're using the image directly without the Ace Link app. 

I made a fix and this time `docker pull blaiseio/acelink:2.0.0` will really do the job :)

**Comment by evmurashov** [comment]
It's ok now, thank you!
