### ISSUE TITLE
I have a problem with casting streams

### ISSUE THREAD

**Issue by cgarroyo03** [blaise-io/acelink#48]
Hi!
When I try to cast any stream, it says that it "cannot get stream title". I have the latest version of Ace Link. Could you tell me what I should do, please?
Thank you very much in advance.

**Comment by blaise-io** [comment]
Which video player do you use? How do you cast?

Maybe ports 6878 and 6888 are not accessible within your local network? 

You could try launching `http://<networkip>:6888/acelink.m3u8` manually on your Chromecast as a workaround after starting a stream, where `<networkip>` is the network IP of the machine running Ace Link.

**Comment by cgarroyo03** [comment]
I use a VLC player on my mac and then I plugged it into the TV. How could I see which port is accessible? I tried to check it with Terminal and it says the connections are refused.  So where can I find the Ace Link network IP? Is it my router one? Thank you very much in advance.
![image](https://user-images.githubusercontent.com/77676000/164977203-86ed6394-bd75-4c61-8f40-8b38a1a391bd.png)

**Comment by blaise-io** [comment]
The Ace Link network IP would be your mac's network IP. You can find it using this guide: https://www.hellotech.com/guide/for/how-to-find-ip-address-on-mac.

**Comment by cgarroyo03** [comment]
It seems that now works. In case the error appears, I will let you know. Thank you!!
