### ISSUE TITLE
[Request] Windows Version

### ISSUE THREAD

**Issue by DrW3b** [blaise-io/acelink#5]
Will be appreciated if you launch it.

Thanks

**Comment by blaise-io** [comment]
Hello @DrW3b, This is intentionally a Mac OS-only project as Ace Stream is not natively supported on Mac OS, whereas it is natively supported on Windows and multiple Linux distributions. [Ace Stream on Windows](http://wiki.acestream.org/wiki/index.php/Download) uses a player based on VLC with Ace Stream opening integrated into the player, why don't you use that?

**Comment by bhavyakenia** [comment]
Ace Link for Windows does not seem to have the Rendering option that VLC has - AceLink on MacOS makes it possible to use it and cast to Chromecast saving the trouble of using a cable to connect to TV etc.
