### ISSUE TITLE
Acestream Engine @ NAS

### ISSUE THREAD

**Issue by evmurashov** [blaise-io/acelink#52]
**Describe the problem you are encountering**
Hi,
I want to run Acestream Engine on my NAS (QNAP D2), but current docker image is not support processor (Annapurna Labs AL-212, ARM Cortex-A15).

**Describe the solution you'd like**
Build docker image for ARM

![image](https://user-images.githubusercontent.com/80024729/169684202-9ee76eab-3dff-4beb-93dd-759a3a5e32cc.png)

**Comment by evmurashov** [comment]
Version ARMv7 (x32)

**Comment by blaise-io** [comment]
Hey @evmurashov,

I'm sorry, this is out of scope for this project, as the goal of Ace Link is to run Acestream on macOS and the AMD64 Docker image required to do so. There's no AMRv7 macOS.

You could try your luck at https://hub.docker.com/search/?q=acestream&type=image&architecture=arm or https://github.com/search?q=acestream+armv7

**Comment by lu4t** [comment]
Hi @evmurashov 
you might want to give a try to this image: https://hub.docker.com/r/inutil/acelu4t built for armv7 and armv8
cheers!
