### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by Githeo** [blaise-io/acelink#55]
Hi,
is there a specific requirement on the docker version?
Docker version 2.3.0.5 (I know quite old but is the one for high sierra) seems not to be recognized:

![Screen Shot 2022-10-01 at 16 04 53](https://user-images.githubusercontent.com/8645265/193413323-f1e8ee94-666e-40dc-be24-aae2793ec1cf.png)

Thank you.

**Comment by damt983** [comment]
Same happends to me

**Comment by hithisisfun** [comment]
did there end up being a way of solving this, the same happens to me.

**Comment by edudediegolucas** [comment]
Same for BigSur:
![imagen](https://user-images.githubusercontent.com/15824105/230996792-86bb7aed-bb3f-4f04-9140-4771f0a2332d.png)

Using 
`$ docker --version
Docker version 20.10.24, build 297e128`

and ace-link app version 2.0.2.

**Comment by blaise-io** [comment]
At all here, can you provide me the output of `osascript -e 'id of app "Docker"'` or `mdls -name kMDItemCFBundleIdentifier -r /Applications/Docker.app`?

**Comment by blaise-io** [comment]
I'm likely detecting whether Docker is installed the wrong way. (https://github.com/blaise-io/acelink/blob/22afdfd6bfd6907810215d026959243a8811c4bc/Ace%20Link/Menu/MainMenu.swift#L48) I did this to support Colima, which is a Docker replacement, instead of detecting a correct BundleID but apparently running `docker` without parameters may exit with an error status.

**Comment by blaise-io** [comment]
@edudediegolucas @viktordavidovich what do you get for `docker; echo $?`?

**Comment by viktordavidovich** [comment]
> @edudediegolucas @viktordavidovich what do you get for `docker; echo $?; which docker`?

@blaise-io I'm getting this `/usr/local/bin/docker` 
Long story short, I had to uninstall docker which has been already installed before ace-link. I've done the same for VLC player (has been installed before) 
Then I called `brew install ace-link --cask  ` and now ace-link works fine.

**Comment by blaise-io** [comment]
Thanks @viktordavidovich. 

I created https://github.com/blaise-io/acelink/releases/download/2.0.3/Ace.Link.2.0.3.dmg which slightly changes the detection of `docker`.

**Comment by edudediegolucas** [comment]
> @edudediegolucas @viktordavidovich what do you get for `docker; echo $?; which docker`?
@blaise-io this where my docker is (I installed via brew long time ago):

`/Applications/Docker.app/Contents/Resources/bin/docker`

Recently, I had to change my PATH env to apps folder because latest docker versions provided the possibility of having binaries in non-sudo folders: I noticed also that when upgrading via brew, it does not ask for sudo password anymore.

And I have updated as well the app to the new 2.0.3 version I have still the _Docker is required..._ message.

**Comment by blaise-io** [comment]
I can solve this but it gets a bit ugly: I can find and run Docker by BundleID, but Ace Link also sort of supports Colima and possibly other runtimes in the future, so then I'd have to list those BundleID's as well. But I don't know which BundleID would be preferred by the user, so then it gets messy. It's probably best to rely for now on the `docker` that's on the PATH.

**Comment by marcosdiak** [comment]
> > @edudediegolucas @viktordavidovich what do you get for `docker; echo $?; which docker`?
> 
> @blaise-io I'm getting this `/usr/local/bin/docker` Long story short, I had to uninstall docker which has been already installed before ace-link. I've done the same for VLC player (has been installed before) Then I called `brew install ace-link --cask ` and now ace-link works fine.

This worked for me too. Thanks.

**Comment by blaise-io** [comment]
For those who don't have `docker` in their path, can you verify this build works? [Ace.Link.2.0.5-bundleid.dmg.zip](https://github.com/blaise-io/acelink/files/11298568/Ace.Link.2.0.5-bundleid.dmg.zip)

If it does not work, please paste the log of Ace Link in this issue. You can retrieve the log like this:

1. Open Console.app
2. In Console.app search box, type `Process: Ace Link` and press enter
3. Click on Start or Start streaming
4. Open this Ace Link build
5. It should now start populating Console.app with debug information, Cmd+A, Cmd+C and then Cmd+V in this issue
