### ISSUE TITLE
docker not being registered by ace link

### ISSUE THREAD

**Issue by hithisisfun** [blaise-io/acelink#60]
I have downloaded docker and signed in etc, same with ace link and have followed all apparent steps to get it to work, however ace link does not appear to be registering that I have docker downloaded. can someone please tell me how to resolve this, thanks
![Uploading Screenshot 2023-03-05 at 10.05.52.png…]()

**Comment by blaise-io** [comment]
Thanks for reporting, I'm investigating as part of #55
