### ISSUE TITLE
v2.0.3 down't not start docker container

### ISSUE THREAD

**Issue by AndrewP-GH** [blaise-io/acelink#62]
**Describe the bug**  
After updating from 2.0.2 to 2.0.3 ace-link doesn't work anymore. I see that the docker container doesn't start.
My PC: macos ventura 13.2.1 — m1 pro
Docker version 20.10.24
Docker Desktop v4.18.0

**Comment by nebelnic** [comment]
Same here with Ventura 13.3 m2

**Comment by blaise-io** [comment]
I will debug next week when I have access to an M1 machine. 

In the meantime 2.0.2 still works?

**Comment by AndrewP-GH** [comment]
yes, 2.0.2 works as expected in this case)

**Comment by AndrewP-GH** [comment]
@blaise-io I've debugged the app and found out that the problem is:
Error: No such image: blaiseio/acelink:2.0.3

**Comment by AndrewP-GH** [comment]
So, to solve this issue we have to add `--platform=linux/amd64` to docker pull command for Apple CPU

**Comment by AndrewP-GH** [comment]
I have made the [PR](https://github.com/blaise-io/acelink/pull/63) to solve this issue. The problem is not in the latest release, this bug has already been with us for a long time :)

**Comment by blaise-io** [comment]
Thanks again @AndrewP-GH. I also tagged 2.0.2 as 2.0.3 for the time being, so a local `docker pull docker.io/blaiseio/acelink:2.0.3` should also fix the issue. I will now publish a 2.0.4 of shame.
