### ISSUE TITLE
Acelink stream on other device (apple TV) not working

### ISSUE THREAD

**Issue by vhclafar** [blaise-io/acelink#64]
Acelink is working fine on my mac and i can watch fine using IINA.

However when i try to play a network stream through VLC on my Apple Tv or iPad it does not start and displays an error, even though it sees streams name.

In VLC i'm entering http://(macbooknetworkip):6888/acelink.m3u8 

any idea what am I doing wrong?

**Comment by blaise-io** [comment]
My guess is that the codec of the video stream is not supported by Apple TV / iPad. 

You can try to visit `http://<macbooknetworkip>:6878/webui/player/(acestreamhash)`. If you cannot access this page at all, you have a network or firewall issue. If it doesn't play, likely the codec is not supported, which you can check by enabling developer tools, and opening the Console in developer tools in your browser.

In VLC on your MacBook, you can see which codec is used. VLC can transcode on the fly, but I have never tried: https://docs.videolan.me/vlc-user/3.0/en/advanced/transcode/transcode_and_stream.html

**Comment by vhclafar** [comment]
for additional info i just tried a different link for my apple tv so rather that link ending acelink.m3u8 i entered http://(macbooknetworkip):6878/ace/getstream?id=acestreamid_entered_here  and now it works on apple tv using vlc

**Comment by blaise-io** [comment]
For future reference, how did you run the Ace Stream server? Through Docker CLI, or by starting Ace Link? 

Because the Docker CLI instructions in the README don't map port 6888, that's an Ace Link addition because some players require the m3u8 to be served over HTTP.

**Comment by vhclafar** [comment]
by running acelink, it automatically starts Docker and then opens IINA, which i then closed (IINA) and entered link on the apple TV.

**Comment by blaise-io** [comment]
Ace Link shuts down the stream when you close IINA. You could try pausing IINA instead, but if https://github.com/blaise-io/acelink/issues/64#issuecomment-1518558031 works for you as well that's likely better because there will be one player consuming the stream.

**Comment by blaise-io** [comment]
Thanks for reporting and debugging!

**Comment by TP18** [comment]
So it is possible to stream from laptop to Apple TV? Could you add it to read me? 👍Thanks!Sent from my iPhoneOn 22 Apr 2023, at 10:43, Blaise Kal ***@***.***> wrote:﻿
Thanks for reporting and debugging!

**Comment by vhclafar** [comment]
my solution works, however it is a bit of a pain to use, as anytime you change a stream you need to change a link on apple tv, so the acelink.m3u8 option is better, but I am not sure why it does not work for me

**Comment by blaise-io** [comment]
If you keep IINA open (pause or stop the stream instead) then you can always use the same m3u8 link.

**Comment by vhclafar** [comment]
i tried that just now and it does not work, my vlc just says " please wait acelink.m3u8" but nothing happens, if i exit and choose it from history it will not even stay on please wait screen for longer than half a second

**Comment by blaise-io** [comment]
Did you launch the stream first in Ace Link? You need to do that to start the engine and populate acelink.m3u8.

**Comment by vhclafar** [comment]
my process is like this: i click on a acestream link, it automatically asks if i want to launch it using acelink, i click yes. once IINA launches and plays the stream i pause it and enter (http://networkip:6888/acelink.m3u8) in the vlc app on the apple tv

**Comment by morelazers** [comment]
In case anyone else comes across this, I made a couple of scripts for making the stream available from my mac to my xbox (via kodi). This probably works for AppleTV etc as well.

```bash
# server.sh
/Applications/Docker.app/Contents/MacOS/Docker\ Desktop.app/Contents/MacOS/Docker\ Desktop

# Function to check if Docker is running
check_docker() {
    docker info >/dev/null 2>&1
}

# Wait for Docker to start
until check_docker; do
    echo "Waiting for Docker to start..."
    sleep 2
done

echo "Docker is running!"

docker run \
  --hostname=e32e90a12e63 \
  --mac-address=02:42:ac:11:00:02 \
  --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  -p 6878:6878 \
  --restart=no \
  --runtime=runc \
  -d \
  blaiseio/acelink:1.5.0
```

And

```
# stream.sh

# Check if the user provided a filename
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path-to-stream-id>"
    exit 1
fi

# Get the filename from the first command-line argument
filename="$1"

# Run VLC with the provided filename
/Applications/VLC.app/Contents/MacOS/VLC -vvv "$filename" --sout '#standard{access=mmsh,mux=asfh,dst=0.0.0.0:9999}'
```

I save stream ids in files, so I use them like this (where `channel-one` is a file containing nothing but an ace id):
```
> ./ace.sh
> ./stream.sh channel-one
```

Then on kodi I load the stream at `mmsh://macbook.ip:9999` and it works like a charm. I'm sure there's probably a way to connect to the ace engine directly from kodi but I found the VLC restream way to be a lot simpler.

**Comment by morelazers** [comment]
In case anyone else comes across this, I made a couple of scripts for making the stream available from my mac to my xbox (via kodi). This probably works for AppleTV etc as well.

```bash
# server.sh
/Applications/Docker.app/Contents/MacOS/Docker\ Desktop.app/Contents/MacOS/Docker\ Desktop

# Function to check if Docker is running
check_docker() {
    docker info >/dev/null 2>&1
}

# Wait for Docker to start
until check_docker; do
    echo "Waiting for Docker to start..."
    sleep 2
done

echo "Docker is running!"

# TODO: Get this command from inside docker desktop when you start ace link normally
docker run \
  --hostname=some:hostname \
  --mac-address=some:mac:addr \
  --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  -p 6878:6878 \
  --restart=no \
  --runtime=runc \
  -d \
  blaiseio/acelink:1.5.0
```

And

```
# stream.sh

# Check if the user provided a filename
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path-to-stream-id>"
    exit 1
fi

# Get the filename from the first command-line argument
filename="$1"

# Run VLC with the provided filename
/Applications/VLC.app/Contents/MacOS/VLC -vvv "$filename" --sout '#standard{access=mmsh,mux=asfh,dst=0.0.0.0:9999}'
```

I save stream ids in files, so I use them like this (where `channel-one` is a file containing nothing but an ace id):
```
> ./ace.sh
> ./stream.sh channel-one
```

Then on kodi I load the stream at `mmsh://macbook.ip:9999` and it works like a charm. I'm sure there's probably a way to connect to the ace engine directly from kodi but I found the VLC restream way to be a lot simpler.

It doesn't delete the container from docker after you're done though, I wasn't sure how to do that.
