### ISSUE TITLE
HLS stream option in Docker image is not working

### ISSUE THREAD

**Issue by lpla** [blaise-io/acelink#65]
**Describe the bug**  
I tried to run my configuration file `acestream.conf`:

```
--allow-user-config
--bind-all
--create-hls-transport
```

But I get this error message in the logs:

```
2023-05-01 11:08:16,684|MainThread|acestream|error during startup
Traceback (most recent call last):
  File "core.c", line 1791, in 
  File "core.c", line 706, in 
  File "core.c", line 23, in 
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

If I replace the `--create-hls-transport` option I added with the default (as per this repository) `--client-console` everything works. But then HLS streaming is not working, which is needed to stream to Safari browser.

**What I expected to happen**  
HLS streaming should work.

**Screenshots**  
…

**Additional debug info**  

The macOS app is not involved in this issue, only the Docker image to create a headless server.

**Comment by blaise-io** [comment]
Can you try the build in this comment and let me know? https://github.com/blaise-io/acelink/issues/79#issuecomment-1975206635
