### ISSUE TITLE
Open link appears greyed out

### ISSUE THREAD

**Issue by tarmangue** [blaise-io/acelink#7]
As the title says, the open link button appears greyed-out. I attach a screenshot.
![screenshot 2018-11-07 at 19 59 29](https://user-images.githubusercontent.com/36964907/48153972-d08beb00-e2c7-11e8-8379-5e40261a1a09.png)

**Comment by blaise-io** [comment]
You need to copy an ace stream id to your clipboard. An ace stream id looks something like cf23df2207d99a74fbe169e3eba035e633b65d94.
