### ISSUE TITLE
Cant run docker engine

### ISSUE THREAD

**Issue by zaraziko** [blaise-io/acelink#73]
hi! i have mac os ventura 13.6 and mac book pro with M1 pro chip
ace cast 2.0.5 after launching ace-link make en Error - Cant run docker Engine.

can you help me - how to watch ace-links on mac os?

**Comment by JavierLeonPeris** [comment]
same problem here, I updated docker this week and I haven't been able to run acelink since then. I have reinstalled everything but same problem, is there a specific docker version that we should use?

Thanks a lot for your work, I have been using this for more than a year.

**Comment by zaraziko** [comment]
> same problem here, I updated docker this week and I haven't been able to run acelink since then. I have reinstalled everything but same problem, is there a specific docker version that we should use?
> 
> Thanks a lot for your work, I have been using this for more than a year.

whats was your version of docker before updating?

**Comment by blaise-io** [comment]
I think I can reproduce, are you also getting this repeatedly when following instructions from https://github.com/blaise-io/acelink#view-ace-link-logs?

```log
default	19:21:27.694092+0200	Ace Link	Running command: docker ps
default	19:21:27.807132+0200	Ace Link	StandardOut:
default	19:21:27.807190+0200	Ace Link	standardError: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by blaise-io** [comment]
I think we're running into https://github.com/docker/for-mac/issues/6529

This works for me: https://github.com/docker/for-mac/issues/6529#issuecomment-1293730577: ` sudo ln -sf "$HOME/.docker/run/docker.sock" /var/run/docker.sock`

**Comment by lares999** [comment]
> If you're running into this issue, please confirm that [Ace.Link.2.0.5-new-sock.dmg.zip](https://github.com/blaise-io/acelink/files/13061553/Ace.Link.2.0.5-new-sock.dmg.zip) fixes the issue.

Can confirm, that worked for me with up-to-date Docker. Thx!

**Comment by JavierLeonPeris** [comment]
it worked for me too, now I'm worried to update docker again haha should it work?

**Comment by andriandreo** [comment]
So it turns out that `docker` for macOS is not like the one for Linux as mentioned [here](https://github.com/docker/for-mac/issues/6980) and you also need `Docker Desktop` (which is not needed in Linux for running the daemon and using and running `docker` images). That's why `ace-link` was not working for me, in case this is helpful for anybody else. 

Great work with this Ace Stream implementation! Much better than the one I used to deal with using an installed version of Wine and the actual Windows software...

**Comment by vishalzambre** [comment]
Apple M1 Sonoma 14.1.1, Docker version 24.0.6, build ed223bc
Diagnostics ID: 7357B5CE-FFC5-48D8-AF74-6F0EFE562645/20231116075020
