### ISSUE TITLE
Cannot run AceStream server

### ISSUE THREAD

**Issue by taymazm** [blaise-io/acelink#74]
It is not possible to run the player after installing latest versions of ace link and docker

<img width="254" alt="Screenshot 2023-10-07 at 15 57 46" src="https://github.com/blaise-io/acelink/assets/54800765/78d77251-2b0f-4df0-b82d-6cf03646b1e5">

**Comment by HorseNamedHorse** [comment]
I've encountered this bug as well. When Ace Link initially launches Docker, the acelink--ace-stream-server container does not appear to be running.

Workaround for me has been to simply try the link a second time. The container then appears in Docker and everything works.

**Comment by taymazm** [comment]
Well in my case Ace Link launches Docker, the acelink--ace-stream-server container appear to be running, but before opening media player (VLC) it gives me that message "Cannot run Acestream server".

**Comment by taymazm** [comment]
> > Well in my case Ace Link launches Docker, the acelink--ace-stream-server container appear to be running, but before opening media player (VLC) it gives me that message "Cannot run Acestream server".
> 
> Yes, I get the same pop-up message, and VLC is not launched at all.
> 
> Does it work if you then click the link again, or launch the link from the Ace Link History menu?


No, it doesn't work. I try again from history or click the link again, same pop-up message.

**Comment by HorseNamedHorse** [comment]
Happy to say Ace Link 2.0.6 looks to have fixed this for me.

**Comment by taymazm** [comment]
- SOLVED - 
I deleted everything and downloaded from beginning.

Now it is working. BUT, when I am connected to VPN I still got problem. With VPN, Docker works, containers work, but the media player (VLC) doesn't start.  I need to log off VPN to start the stream.
