### ISSUE TITLE
Broken link with VLC

### ISSUE THREAD

**Issue by HubSte** [blaise-io/acelink#78]
The "Open stream from clipboard" option is grayed out
…  

Note: Don't share AceStream IDs or websites containing pirated content.

With Docker Desktop installed , Ace Link used to open copied Ace links and open VLC automatically through Docker, but now the option to paste an Ace link is grayed out and  I don't know what to do.
…

**Screenshots**  
…

**Additional debug info**  

1. Open Console.app
2. In the Console.app search field, type `Process: Ace Link`
3. Click on *Start* or *Start streaming*
4. Launch Ace Link, open stream that failed previously — if this is your issue
5. It should now start populating Console.app with debug information, Cmd+A, Cmd+C 
6. Replace this entire list with Cmd+V.

**Comment by blaise-io** [comment]
You need to have a valid Acestream link in your clipboard.
