### ISSUE TITLE
Detect VLC installations from other than the main Applications director

### ISSUE THREAD

**Issue by jeremymeyers** [blaise-io/acelink#8]
I have my VLC in a subdirectory inside my applications folder, and Ace Link does not see it and therefore cannot run correctly. Would be nice to be able to browse for VLC if its not found in the main applications directory.

**Comment by blaise-io** [comment]
Thanks for reporting, I will fix this at some point.

If you're interested in a workaround: create a symbolic link: open Terminal app, type `sudo ln -s /path/to/your/VLC.app /Applications/VLC.app`

**Comment by blaise-io** [comment]
This issue should be resolved in 1.4.0

https://github.com/blaise-io/acelink/releases/download/1.4.0/Ace.Link.1.4.0.dmg
