### ISSUE TITLE
simplified network stream url for iPad

### ISSUE THREAD

**Issue by RW58** [blaise-io/acelink#83]
hi,

i am using this for a few weeks now and its working great!
But when I want to view the stream on for example an iPad I have to copy the acestream id to the VLC player app on the iPad and past it after the local url of the docker container: http://192.168.x.y:6878/ace/getstream?id=[acestream id] and that's a bit complex.
It would be much easier to use a simplified url that doesn't have to contain the acestream id. Is it possible?

Many thanks!

**Comment by RW58** [comment]
I've found http://192.168.x.y:6888/acestream.m3u8 but it contains a link to http://127.0.0.1:6878/ace/getstream?id=[acestream id] which does not work on another device like an iPad. Is it possible to change the url in the acestream.m3u8 file?

**Comment by blaise-io** [comment]
You can access the url exposed inside the m3u with your iPad. Make sure to use an app that supports the codec of the stream. On 17 Apr 2024, at 08:29, RW58 ***@***.***> wrote:﻿
I've found http://192.168.x.y:6888/acestream.m3u8 but it contains a link to http://127.0.0.1:6878/ace/getstream?id=[acestream id] which does not work on another device like an iPad. Is it possible to change the url in the acestream.m3u8 file?

**Comment by RW58** [comment]
Thank you for your reply! Since the url exposed in the m3u contains 127.0.0.1 I can't use it on my iPad because 127.0.0.1 is localhost which would be the iPad itself. How can I change the url in the m3u?

**Comment by blaise-io** [comment]
Use your Mac's local network IP instead of 127.0.0.1, it's the IP address that is listed when you click the wifi/internet icon in your menu bar while pressing the Option key, or Google "Find network IP on macos".

**Comment by RW58** [comment]
I know how to find the ip address of my Mac :-) The question is whether or not it's possible to get the ip address of my Mac in the m3u8 list?
