### ISSUE TITLE
Errors and instability under VPN

### ISSUE THREAD

**Issue by litio2001** [blaise-io/acelink#85]
When I launch the container connected under VPN (using Gluetun container) in the acelink log I see many errors that are not shown when I do NOT use VPN.

I Paste container log acelink:
*(I have replaced the link ID with XXXX for privacy)
```shell
2024-04-11 20:06:01,464|ServiceBrowserThread-24|zc|run: got socket error
2024-04-11 20:06:21,464|ServiceBrowserThread-24|zc|run: got socket error
2024-04-11 20:06:24,303|AceStreamCoreThread|acestream.live.download.XXXXXXXXXXXXX|send_multicast_pex_announce: error: <class 'PermissionError'>:[Errno 1] Operation not permitted
2024-04-11 20:06:41,464|ServiceBrowserThread-24|zc|run: got socket error
2024-04-11 20:07:01,464|ServiceBrowserThread-24|zc|run: got socket error
2024-04-11 20:07:16,361|AceStreamCoreThread|acestream.live.download.XXXXXXXXXXXXX|send_multicast_pex_announce: error: <class 'PermissionError'>:[Errno 1] Operation not permitted
2024-04-11 20:07:21,464|ServiceBrowserThread-24|zc|run: got socket error
2024-04-11 20:07:24,309|AceStreamCoreThread|acestream.live.download.XXXXXXXXXXXXX|send_multicast_pex_announce: error: <class 'PermissionError'>:[Errno 1] Operation not permitted
``` 

These errors when not connected by VPN are not displayed.
However, even with these errors the playback usually works, but when many errors begin to appear it begins to be unstable.
Since it is a paid VPN, I can configure it by removing the security filters (ad blocking, etc.), activating NAT and port forwarding:

![imagen](https://github.com/blaise-io/acelink/assets/80854173/4d44d6e0-2a53-4f36-84b6-f2cb1aa4a2cb)

More data:
1- I use paid ProtonVPN (Wireguard protocol).
2- The acelink container is associated with the Gluetun container network.
3- My host system is a Synology DS920+

I paste my docker compose (I use portainer):

```dockerfile
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    mem_limit: 1g
    cpu_shares: 768
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy #For gluetun container
      - 8388:8388/tcp # Shadowsocks #For gluetun container
      - 8388:8388/udp # Shadowsocks #For gluetun container
      - 6878:6878 #For acestream container
      - 8621:8621 #For acestream container
      - 62062:62062 #For acestream container

    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - TZ=Europe/Madrid
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=XXX.XXX.XXX.XXX
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=XXXXX
      - WIREGUARD_PRIVATE_KEY=XXXX
      - WIREGUARD_ADDRESSES=XX.X.X.X/XX
      - DNS_ADDRESS=X.X.X.X
      - WIREGUARD_MTU=XXXX
    networks:
      - gluetun-bridge #It is the network previously created expressly for gluetun.
networks:
      gluetun-bridge:
       external: true
``` 

```dockerfile
version: '3.3'
services:
   blaiseio-acelink:
    image: blaiseio/acelink:2.0.7-a1
    container_name: acestream
    mem_limit: 1g
    cpu_shares: 768
   #ports: (Disabled when connecting to VPN)
    #- 6878:6878 
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/acelink:/config
    restart: always
    network_mode: "container:gluetun" # to join gluetun container network
```

**Comment by blaise-io** [comment]
Acestream is P2P, maybe your VPN provider limits the number of concurrent connections? I don't think I will be able to fix this in Ace Link.

**Comment by blaise-io** [comment]
Can you try this beta build? https://github.com/blaise-io/acelink/issues/79#issuecomment-2095934318

**Comment by litio2001** [comment]
> Can you try this beta build? [#79 (comment)](https://github.com/blaise-io/acelink/issues/79#issuecomment-2095934318)

I am testing the version:
docker pull blaiseio/acelink:2.1.0
I will confirm shortly if it is stable.

**Comment by blaise-io** [comment]
Thanks!

**Comment by antoniozh** [comment]
Hi, I'm having the same issues under VPN using PIA, the external IP and port (assigned to me) are reachable, but I'm still getting some errors. 
I suspect that it is either the alternate port (in this case 50411) that was assigned to me or that something with UPnP is messing with me. 
I already set the P2P port as a flag in acestream.conf, is there any way to disable UPnP or make the error log more verbose? 
These are my logs.
```
2024-10-04 23:34:23,229|Thread-19|acestream.upnp|Unable to create Port Forward. Error: Success: <class 'Exception'>:Success

2024-10-04 23:34:30,748|ServiceBrowserThread-24|zc|run: got socket error

2024-10-04 23:34:31,215|AceStreamCoreThread|acestream.live.download.<streamid>|send_multicast_pex_announce: error: <class 'PermissionError'>:[Errno 1] Operation not permitted
```

**Comment by krinkuto11** [comment]
> Hi, I'm having the same issues under VPN using PIA, the external IP and port (assigned to me) are reachable, but I'm still getting some errors. I suspect that it is either the alternate port (in this case 50411) that was assigned to me or that something with UPnP is messing with me. I already set the P2P port as a flag in acestream.conf, is there any way to disable UPnP or make the error log more verbose? These are my logs.
> 
> ```
> 2024-10-04 23:34:23,229|Thread-19|acestream.upnp|Unable to create Port Forward. Error: Success: <class 'Exception'>:Success
> 
> 2024-10-04 23:34:30,748|ServiceBrowserThread-24|zc|run: got socket error
> 
> 2024-10-04 23:34:31,215|AceStreamCoreThread|acestream.live.download.<streamid>|send_multicast_pex_announce: error: <class 'PermissionError'>:[Errno 1] Operation not permitted
> ```

Did you happen to find a fix for this?

**Comment by antoniozh** [comment]
Sadly no, maybe another provider could work

**Comment by krinkuto11** [comment]
I managed to find a solution to this.

**Port Forwarding**

Obtain the open port from the Gluetun container via its API [Gluetun wiki](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md)
Start the acestream engine with the --port flag with the port you receive.

**Multicast errors**

Add this to the gluetun compose in the env variables sections:
`        - FIREWALL_OUTBOUND_SUBNETS=224.0.0.0/4
`
