### ISSUE TITLE
Stream breaks down at 12 minutes

### ISSUE THREAD

**Issue by janderklanderr** [blaise-io/acelink#88]
**Describe the bug**  
Using docker and acelink

Note: Don't share AceStream IDs or websites containing pirated content.

**What I expected to happen**  
…

**Screenshots**  
…

**Additional debug info**  

1. Open Console.app
2. In the Console.app search field, type `Process: Ace Link`
3. Click on *Start* or *Start streaming*
4. Launch Ace Link, open stream that failed previously — if this is your issue
5. It should now start populating Console.app with debug information, Cmd+A, Cmd+C 
6. Replace this entire list with Cmd+V.

**Comment by blaise-io** [comment]
No logs provided.
